### ISSUE TITLE
Имена

### ISSUE THREAD

**Issue by kate-fsd** [SergeyVN94/slider#3]
1. convertValuesForMinMax не очень удачное название, max там даже не участвует. Можно convertNumberValues

2. isCorrectValues, isNeedUpdateBgLine, isValuesUpdated, pointSteps

3. countPoints - очень похоже на название функции, лучше pointsCount или pointsNumber

4. view.onSelect не подходит по смыслу - изменился/сдвинулся бегунок/...

5. _setViewName (в BgLine) - этот метод не устанавливает название вида, он задает метод update. И лучше этот метод присвоить в конструкторе, чтоб было нагляднее.
В других классах тоже вижу _setViewName, и тоже не то делает

6. _getStart в Point - неудачное имя. Тут ты вроде находишь позицию

7. _horizontalViewSetPosition и все подобные ему. Имя должно начинаться с глагола

8. Файл classes во вью, проверь модификаторы

**Comment by kate-fsd** [comment]
isAllPointsInOnePosition

**Comment by kate-fsd** [comment]
isNeedingUpdateBgLine не принято с need использовать ing окончание. Можно needToUpdate..  такая конструкция тоже удовлетворяет правилам именования булевых

**Comment by kate-fsd** [comment]
еще slider.onSelect

**Comment by kate-fsd** [comment]
getPointPositions  points и исправь все похожие места

**Comment by kate-fsd** [comment]
slider.onMousedown(this._handleSliderSelect.bind(this));   
handleSliderSelect похоже на "обработать выбор слайдера"

**Comment by kate-fsd** [comment]
> getPointPositions points и исправь все похожие места

не исправил

**Comment by SergeyVN94** [comment]
1645abc4fdb34c265c224317e0d9760d4e27369a
