### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by kate-fsd** [SergeyVN94/slider#4]
1. Метод convertValuesForCustomScale преобразует values в строки, а если не получается - возвращает весь массив customScale. То есть если ввести невалидный values, бегунки должны поставиться на все деления шкалы?

2. Здесь лучше брать значения из дефолтного конфига. В модели тоже
![image](https://user-images.githubusercontent.com/66846004/88697182-ddd8b100-d10c-11ea-9ee2-343a1c7364d8.png)

3. Я тебе покажу общий принцип на одном примере, если есть подобные ошибки, исправь их тоже
Есть функция convertConfig. В нее передается конфиг с типом ISliderConfig. Но фактически туда может быть передано  что угодно, так что лучше ему задать тип unknown. Дальше - то же самое 
![image](https://user-images.githubusercontent.com/66846004/88698698-0b265e80-d10f-11ea-9f45-862dbec79e83.png)
(Еще as не рекомендуется использовать без необходимости) convertValuesForCustomScale ожидает два массива из строк. Если убираем as получаем ошибку. Вторым аргументом передаешь тоже не обязательно массив строк, но у тебя уже есть обработанный newConfig.customScale, используй его.

4. Сделай left для slider__point тоже в процентах, тогда сможешь избавиться от всего что связано с ресайзом

5. Наведи порядок в папке scale-drivers. Два одинаковых файла, непонятные названия

6. Для создания копии массива лучше использовать оператор расширения [ ...arr], не slice

**Comment by kate-fsd** [comment]
Третий пункт не исправил, картинка того же места просто для примера, есть еще
![image](https://user-images.githubusercontent.com/66846004/89337332-71792700-d6a3-11ea-9fb3-b9221b3252c4.png)

**Comment by kate-fsd** [comment]
Если вызывать слайдер без values получаю красное предупреждение. Вполне возможна ситуацию, когда пользователю не важно, где изначально стоят бегунки. Лучше в таком случае не выводить ошибку. А уже если пользователь вместо массива в values передал что то другое - тогда нужно.

Вызываю 
![image](https://user-images.githubusercontent.com/66846004/89711420-e776da00-d992-11ea-8730-e0c7ba5fd5a3.png)
Ошибка
![image](https://user-images.githubusercontent.com/66846004/89711449-083f2f80-d993-11ea-8288-9ac6414b80b1.png)

**Comment by kate-fsd** [comment]
Проверь все методы, ожидаемо ли они работают. Сделай сейчас readme, с описанием как подключить и как пользоваться.

Метод 'min-max'. Для того чтобы поменять мин мне нужно обязательно передать макс, и наоборот. Это неудобно. Сделай так чтоб можно было менять их поодиночке

**Comment by kate-fsd** [comment]
> Если вызывать слайдер без values получаю красное предупреждение.

Так и осталось

**Comment by kate-fsd** [comment]
И, наоборот, если шаг превышает (макс - мин) ошибка не показана (еще мин > макс, шаг равен нулю, шаг/мин/макс не целое, макс равен мин...)

Еще можно такие данные обработать values: "[0, 1, 2]"

**Comment by kate-fsd** [comment]
При обновлении слайдера тоже нет ошибок

**Comment by kate-fsd** [comment]
В модели
public static readonly NO_ERROR = 0;

Кажется ты это используешь только для того, чтобы typescript не ругался. Везде, где ты return 0;, лучше возвращай undefined, если нет ошибки

**Comment by kate-fsd** [comment]
for (let i = 0; i < values.length; i += 1)
Везде где ты используешь for для перебора массива, замени его на специальные методы перебора массивов https://learn.javascript.ru/array-methods
Пример:
![image](https://user-images.githubusercontent.com/66846004/90674680-209c2d80-e262-11ea-9f49-140f9ddcba47.png)

**Comment by kate-fsd** [comment]
Файл Controller
![image](https://user-images.githubusercontent.com/66846004/91316817-f39bcd80-e7c1-11ea-9a2c-86163227748c.png)
Аналогичная ситуация с непонятной константой. Если нет выбранных бегунков, присваивай null

**Comment by kate-fsd** [comment]
Еще похожее
![image](https://user-images.githubusercontent.com/66846004/91317333-96ece280-e7c2-11ea-80b6-f506e72ac0b9.png)

Если они по дефолту стоят в начале можно 0

**Comment by SergeyVN94** [comment]
9da38f0047be0e7aa95b2a5a48f3ab7e6fb9c499
